title: Evolution for Everyone
description: Empowering diverse scientists in evolutionary biology 
theme: just-the-docs

url: https://Evolution-for-Everyone.github.io/evolution4everyone

aux_links:
  Template Repository: https://github.com/Evolution-for-Everyone/evolution4everyone
