title: Evolution for Everyone
description: Empowering diverse scientists in evolutionary biology 
theme: just-the-docs

url: https://leticiamagpali.github.io/evolution4everyone

aux_links:
  Template Repository: https://github.com/leticiamagpali/evolution4everyone
